### ISSUE TITLE
Missing test images

### ISSUE THREAD

**Issue by jayvdb** [AzHicham/openslide-rs#178]
Hiya, Running `cargo test` I see

```
---- test_hamamatsu_properties::case_1 stdout ----
thread 'test_hamamatsu_properties::case_1' panicked at tests/properties.rs:437:42:
called `Result::unwrap()` on an `Err` value: MissingFile("tests/assets/hamamatsu/CMU-3-40x - 2010-01-12 13.57.09.vms")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_mirax_properties::case_1 stdout ----
thread 'test_mirax_properties::case_1' panicked at tests/properties.rs:365:42:
called `Result::unwrap()` on an `Err` value: MissingFile("tests/assets/mirax/CMU-1-Saved-1_16.mrxs")

---- test_leica_properties::case_1 stdout ----
thread 'test_leica_properties::case_1' panicked at tests/properties.rs:205:42:
called `Result::unwrap()` on an `Err` value: MissingFile("tests/assets/leica.scn")

---- test_trestle_properties::case_1 stdout ----
thread 'test_trestle_properties::case_1' panicked at tests/properties.rs:318:42:
called `Result::unwrap()` on an `Err` value: MissingFile("tests/assets/trestle/CMU-1.tif")
```

**Comment by AzHicham** [comment]
Hello, 

I need to update instruction but in order to run tests you have to run this command: 
`make dl-test-images`
Note: this can take some time but in the CI test data are always cached https://github.com/AzHicham/openslide-rs/actions/runs/11322570042/workflow#L41
